informix_db_url=jdbc:informix-sqli://qa-ram0000-ce07.autozone.com:5004/azrims00:INFORMIXSERVER=azbillwinsoc

#QAInformix details updated in below
qa_Informix_host = qa-ram0000-ce07.autozone.com
qa_Informix_port = 5004
qa_Informix_DbName = azrims00:INFORMIXSERVER=azbillwinsoc 
qa_Informix_userName=gls
qa_Informix_password=istsfr?